# realize.dockerfile
FROM golang:1.11.1-alpine3.8

RUN apk --update add git bash build-base && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

WORKDIR /app
VOLUME /app

RUN go get github.com/oxequa/realize

CMD ["realize", "start"]
