//go:generate stringer -type=ServerType,DatabaseType -output=types_string.go
package internal

const (
	// nexus
	camundaNexusMavenGAVSearchUrl = "https://app.camunda.com/nexus/service/local/artifact/maven/redirect"
	CamundaNexus                  = "https://app.camunda.com/nexus"
	CamundaOSSRepo                = "camunda-bpm"
	CamundaEERepo                 = "camunda-bpm-ee"
	CamundaPublicGroup            = "public"
	CamundaPrivateGroup           = "private"
	CamundaInternalGroup          = "internal"
	// docker
	CamundaDockerRegistry = "https://registry.camunda.com"
)

// Type of the server, determined according to path of URL, go generated by stringer
type ServerType int
type DatabaseType int

const (
	Tomcat ServerType = iota
	JBoss
	Wildfly
	JBossEAP
	WebLogic
	WebSphere

	H2 DatabaseType = iota
	MySQL
	MariaDB
	PostgresSQL
	DB2
	Oracle
)

func DetermineServerType(server Server) ServerType {
	return 0
}

func DetermineDatabaseType(database Database) DatabaseType {
	return 0
}
