// Code generated by "stringer -type=ServerType,DatabaseType -output=types_string.go"; DO NOT EDIT.

package internal

import "strconv"

const _ServerType_name = "TomcatJBossWildflyJBossEAPWebLogicWebSphere"

var _ServerType_index = [...]uint8{0, 6, 11, 18, 26, 34, 43}

func (i ServerType) String() string {
	if i < 0 || i >= ServerType(len(_ServerType_index)-1) {
		return "ServerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerType_name[_ServerType_index[i]:_ServerType_index[i+1]]
}

const _DatabaseType_name = "H2MySQLMariaDBPostgresSQLDB2Oracle"

var _DatabaseType_index = [...]uint8{0, 2, 7, 14, 25, 28, 34}

func (i DatabaseType) String() string {
	i -= 6
	if i < 0 || i >= DatabaseType(len(_DatabaseType_index)-1) {
		return "DatabaseType(" + strconv.FormatInt(int64(i+6), 10) + ")"
	}
	return _DatabaseType_name[_DatabaseType_index[i]:_DatabaseType_index[i+1]]
}
